### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by Drjacky** [gumiguelote/gnib-irp-telegram#1]
I used Github for the Deployment method in the Heroku and deployed. And when I visit the page, I see:
<img width="138" alt="Screen Shot 2021-12-16 at 13 05 39" src="https://user-images.githubusercontent.com/2296754/146377295-d4d33158-40c2-4db8-8170-c6fe108a4a33.png">

**Comment by gumiguelote** [comment]
Hi @Drjacky , sorry for the late reply, this project doesn't have a web interface yet, all interactions with the service are by the commands in the telegram bot.

If you want to improve with some suggestions, be free to submit a PR
